package io.github.appspiriment.kolt.composekmp.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.colorResource
import io.github.appspiriment.kolt.composekmp.R
import io.github.appspiriment.kolt.composekmp.wrappers.uiColorResource

@Composable
actual fun baseColors(isDarkTheme: Boolean) = BaseColors(
    primary = colorResource(id = R.color.primary),
    onPrimary = colorResource(id = R.color.onPrimary),
    secondary = colorResource(id = R.color.secondary),
    onSecondary = colorResource(id = R.color.onSecondary),
    tertiary = colorResource(id = R.color.tertiary),
    onTertiary = colorResource(id = R.color.onTertiary),
    scrimColor = colorResource(id = R.color.scrim),
    iconTint = colorResource(id = R.color.iconTint),
    disabledIconTint = colorResource(id = R.color.disabledIconTint),
    drawerItem = colorResource(id = R.color.drawerItem),
    navigationBarColor = colorResource(id = R.color.navigationBar),
    mainSurface = colorResource(id = R.color.mainSurface),
    onMainSurface = colorResource(id = R.color.onMainSurface),
    secondarySurface = colorResource(id = R.color.secondarySurface),
    onSecondarySurface = colorResource(id = R.color.onSecondarySurface),
    background = colorResource(id = R.color.background),
    onBackground = colorResource(id = R.color.onBackground),
    primaryCardContainer = colorResource(id = R.color.primaryCardContainer),
    onPrimaryCardContainer = colorResource(id = R.color.onPrimaryCardContainer),
    onPrimaryCardContainerDimmed = colorResource(id = R.color.onPrimaryCardContainerDimmed),
    secondaryCardContainer = colorResource(id = R.color.secondaryCardContainer),
    onSecondaryCardContainer = colorResource(id = R.color.onSecondaryCardContainer),
    tertiaryCardContainer = colorResource(id = R.color.tertiaryCardContainer),
    onTertiaryCardContainer = colorResource(id = R.color.onTertiaryCardContainer),
    greyCardContainer = colorResource(id = R.color.greyCardContainer),
    onGreyCardContainer = colorResource(id = R.color.onGreyCardContainer),
    error = colorResource(id = R.color.error),
    onError = colorResource(id = R.color.onError),
    errorCardContainer = colorResource(id = R.color.errorCardContainer),
    onErrorCardContainer = colorResource(id = R.color.onErrorCardContainer),
    accentedBlueTitle = colorResource(id = R.color.accentedBlueTitle),
    accentedBlackTitle = colorResource(id = R.color.accentedBlackTitle),
    accentedRedTitle = colorResource(id = R.color.accentedRedTitle),
    accentedBlueText = colorResource(id = R.color.accentedBlueText),
    accentedRedText = colorResource(id = R.color.accentedRedText),
    accentedGoldText = colorResource(id = R.color.accentedGoldText),
    topAppBar = colorResource(id = R.color.topAppBar),
    onTopAppBar = colorResource(id = R.color.onTopAppBar),
    disabledText = colorResource(id = R.color.disabledText),
    subText = colorResource(id = R.color.subText),
    hintText = colorResource(id = R.color.hintText),
    dividerColor = colorResource(id = R.color.dividerColor)
)

@Composable
actual fun baseUiColors(isDarkTheme: Boolean) = BaseUiColors(
    primary = uiColorResource(id = R.color.primary),
    onPrimary = uiColorResource(id = R.color.onPrimary),
    secondary = uiColorResource(id = R.color.secondary),
    onSecondary = uiColorResource(id = R.color.onSecondary),
    tertiary = uiColorResource(id = R.color.tertiary),
    onTertiary = uiColorResource(id = R.color.onTertiary),
    scrimColor = uiColorResource(id = R.color.scrim),
    iconTint = uiColorResource(id = R.color.iconTint),
    disabledIconTint = uiColorResource(id = R.color.disabledIconTint),
    drawerItem = uiColorResource(id = R.color.drawerItem),
    navigationBarColor = uiColorResource(id = R.color.navigationBar),
    mainSurface = uiColorResource(id = R.color.mainSurface),
    onMainSurface = uiColorResource(id = R.color.onMainSurface),
    secondarySurface = uiColorResource(id = R.color.secondarySurface),
    onSecondarySurface = uiColorResource(id = R.color.onSecondarySurface),
    background = uiColorResource(id = R.color.background),
    onBackground = uiColorResource(id = R.color.onBackground),
    primaryCardContainer = uiColorResource(id = R.color.primaryCardContainer),
    onPrimaryCardContainer = uiColorResource(id = R.color.onPrimaryCardContainer),
    onPrimaryCardContainerDimmed = uiColorResource(id = R.color.onPrimaryCardContainerDimmed),
    secondaryCardContainer = uiColorResource(id = R.color.secondaryCardContainer),
    onSecondaryCardContainer = uiColorResource(id = R.color.onSecondaryCardContainer),
    tertiaryCardContainer = uiColorResource(id = R.color.tertiaryCardContainer),
    onTertiaryCardContainer = uiColorResource(id = R.color.onTertiaryCardContainer),
    greyCardContainer = uiColorResource(id = R.color.greyCardContainer),
    onGreyCardContainer = uiColorResource(id = R.color.onGreyCardContainer),
    errorCardContainer = uiColorResource(id = R.color.errorCardContainer),
    onErrorCardContainer = uiColorResource(id = R.color.onErrorCardContainer),
    accentedBlueTitle = uiColorResource(id = R.color.accentedBlueTitle),
    accentedBlackTitle = uiColorResource(id = R.color.accentedBlackTitle),
    accentedRedTitle = uiColorResource(id = R.color.accentedRedTitle),
    topAppBar = uiColorResource(id = R.color.topAppBar),
    onTopAppBar = uiColorResource(id = R.color.onTopAppBar),
    disabledText = uiColorResource(id = R.color.disabledText),
    subText = uiColorResource(id = R.color.subText),
    hintText = uiColorResource(id = R.color.hintText),
    accentedBlueText = uiColorResource(id = R.color.accentedBlueText),
    accentedRedText = uiColorResource(id = R.color.accentedRedText),
    accentedGoldText = uiColorResource(id = R.color.accentedGoldText),
    error = uiColorResource(id = R.color.error),
    onError = uiColorResource(id = R.color.onError),
    dividerColor = uiColorResource(id = R.color.dividerColor)
)
